max_width = 118
fn_params_layout = "Compressed"
newline_style = "Native"
reorder_imports = true
reorder_modules = true
style_edition = "2024"
tab_spaces = 2
use_field_init_shorthand = true
use_try_shorthand = true
match_block_trailing_comma = true
unstable_features = true
# empty_item_single_line = false, 这条直接执行和通过precommit hook执行效果不同
# enum_discrim_align_threshold = 20
# struct_field_align_threshold = 20
# force_multiline_blocks = true， 这条直接执行和通过precommit hook执行效果不同
format_generated_files = false
hex_literal_case = "Lower"
imports_granularity = "Module" # Crate 不好用
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
