[package]
name = "redis_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
redis = { version = "0.32.7", features = ["tokio-comp"] }
tokio = { version = "1.48.0", features = ["rt-multi-thread", "macros"] }
